### ISSUE TITLE
panic when parsing malformed enex file

### ISSUE THREAD

**Issue by retpoline** [wormi4ok/evernote2md#61]
I noticed during testing that evernote2md crashes when parsing certain enex files. This could especially be a problem if for example evernote2md is called by a web service, allowing a user to cause crashes on the backend. I've minimized the original crashing file down to this version for simplicity.

**test.enex**
```
<en-export d=""a=""n=""><note><title></title><content><![CDATA[<a><div style="-en-codeblock:true"><div style="-en-codeblock:true"></e>èè]]></r>
```

```
$ evernote2md test.enex

panic: parseHtml: html: inconsistent Node: DataAtom="div", Data="pre"

goroutine 1 [running]:
github.com/wormi4ok/evernote2md/internal.parseOne(0x625ec8, 0x1, 0xc0000db180, 0x625e00)
	/home/runner/work/evernote2md/evernote2md/internal/replace.go:108 +0x14b
github.com/wormi4ok/evernote2md/internal.(*Code).ReplaceTag.func1(0xc0000db1f0)
	/home/runner/work/evernote2md/evernote2md/internal/replace.go:127 +0xa9
github.com/wormi4ok/evernote2md/internal.(*Code).ReplaceTag(0x7a9ee8, 0xc0000db1f0)
	/home/runner/work/evernote2md/evernote2md/internal/replace.go:133 +0x82
github.com/wormi4ok/evernote2md/internal.(*Converter).normalizeHTML.func1(0xc0000db1f0)
	/home/runner/work/evernote2md/evernote2md/internal/replace.go:32 +0x73
github.com/wormi4ok/evernote2md/internal.(*Converter).normalizeHTML.func1(0xc0000db180)
	/home/runner/work/evernote2md/evernote2md/internal/replace.go:35 +0xa6
github.com/wormi4ok/evernote2md/internal.(*Converter).normalizeHTML.func1(0xc0000db110)
	/home/runner/work/evernote2md/evernote2md/internal/replace.go:35 +0xa6
github.com/wormi4ok/evernote2md/internal.(*Converter).normalizeHTML.func1(0xc0000db030)
	/home/runner/work/evernote2md/evernote2md/internal/replace.go:35 +0xa6
github.com/wormi4ok/evernote2md/internal.(*Converter).normalizeHTML.func1(0xc0000dafc0)
	/home/runner/work/evernote2md/evernote2md/internal/replace.go:35 +0xa6
github.com/wormi4ok/evernote2md/internal.(*Converter).normalizeHTML(0xc000096380, 0xc0000ceb40, 0xc00008a4b0, 0xc00017bda8, 0x5, 0x5)
	/home/runner/work/evernote2md/evernote2md/internal/replace.go:38 +0x1ac
github.com/wormi4ok/evernote2md/internal.(*Converter).Convert(0xc000096380, 0xc0000ceb40, 0xc00017be88, 0x1, 0x1)
	/home/runner/work/evernote2md/evernote2md/internal/convert.go:79 +0x1c9
main.run(0xc000074500, 0x1, 0x1, 0xc00017bf58, 0xc0000e4000, 0xc000096380)
	/home/runner/work/evernote2md/evernote2md/main.go:83 +0x28a
main.main()
	/home/runner/work/evernote2md/evernote2md/main.go:68 +0x66a
```

Expected outcome: no crash
Actual outcome: crash

**Comment by wormi4ok** [comment]
Thanks for reporting @retpoline; this looks like a logical issue in code and should be not hard to fix. 🙌🏻
